
services:
      
  radar-okx:
    image: ${REGISTRY:-bidenradar}/okx:${TAG:-latest}
    container_name: radar-okx
    build:
      context: .
      dockerfile: Biden.Radar.OKX/Dockerfile
    networks:
      - bidenradar
    
  radar-bybit:
    image: ${REGISTRY:-bidenradar}/bybit:${TAG:-latest}
    container_name: radar-bybit
    build:
      context: .
      dockerfile: Biden.Radar.Bybit/Dockerfile
    networks:
      - bidenradar
      
  radar-gate:
    image: ${REGISTRY:-bidenradar}/gate:${TAG:-latest}
    container_name: radar-gate
    build:
      context: .
      dockerfile: Biden.Radar.Gate/Dockerfile
    networks:
      - bidenradar
  
  radar-binance:
    image: ${REGISTRY:-bidenradar}/binance:${TAG:-latest}
    container_name: radar-binance
    build:
      context: .
      dockerfile: Biden.Radar.Binance/Dockerfile
    networks:
      - bidenradar
            
networks:
  bidenradar:
    name: bidenradar-network
